### ISSUE TITLE
Fails under Initialize dependencies w Network error

### ISSUE THREAD

**Issue by psimondk** [firecmsco/firecms#521]
Hi,
Awesome project :) - tried to start a new 2.0 project and it got stuck in 'Install dependencies'

? Initialize a git repository? Yes
  ✔ Copy project files
  ✔ Initialize git
  ⠦ Install dependencies
  info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at makeError (/Users/psi/.config/yarn/global/node_modules/pkg-install/node_modules/execa/index.js:174:9)
    at /Users/psi/.config/yarn/global/node_modules/pkg-install/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  
  I'm in Sofia in EST

**Comment by psimondk** [comment]
All due to a too old installation of node / npm / yarn - all good now :)
