### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by VisetDev** [firecmsco/firecms#615]
Trying to add a image storage field from a document property:

`onFetch {profile_url: 'artists/imgs/profile/prof (1).jpg'}`  <--- entity

```
const profile_url = buildProperty({
    dataType: "string",
    name: "URL",
    id: "profile_url",
    propertyConfig: 'file_upload',
    storage: {
        storagePath: '/',
    },
});
```

results in:

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at tde (StorageThumbnail.tsx:77:15)
    at ede (StorageThumbnail.tsx:58:49)

![image](https://github.com/firecmsco/firecms/assets/108474478/097062c3-5d29-4832-ba75-c89c32b58015)

![image](https://github.com/firecmsco/firecms/assets/108474478/ac38942f-435b-4fc5-9654-587f5df0a2ff)

this is deployed to app.firecms.co (it also happens in dev)
hope it's clear enough.
tx

**Comment by VisetDev** [comment]
hi @fgatti675 ! 
found this: https://github.com/firecmsco/firecms/issues/550#issuecomment-1932606634

it has to do with the file type setting.
