### ISSUE TITLE
TypeError: r.indexOf is not a function

### ISSUE THREAD

**Issue by kaustubh-truestate** [firecmsco/firecms#616]
(!important)
I am trying to create a collection called `Estate Properties` and when I try to import data from xlsx file or json file the preview screen shows the data correctly and as soon as I click Next, the screen goes black and upon inspecting I am getting the following error
"
react-dom.production.min.js:127 Uncaught TypeError: r.indexOf is not a function
    at k.fromString (path.ts:239:16)
    at sm (reference.ts:589:20)
    at Object.saveEntity (useFirestoreDelegate.ts:461:37)
    at Object.saveEntity (useBuildDataSource.ts:228:29)
    at ImportSaveInProgress.tsx:80:20
    at Array.map (<anonymous>)
    at Fd (ImportSaveInProgress.tsx:79:30)
    at c (ImportSaveInProgress.tsx:31:9)
    at ImportSaveInProgress.tsx:45:14
    at br (react-dom.production.min.js:244:332)
    at Yn (react-dom.production.min.js:286:111)
    at Sf (react-dom.production.min.js:283:409)
    at hn (react-dom.production.min.js:281:398)
    at wo (react-dom.production.min.js:273:439)
    at dn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
"

I have checked every field and it's datatype.

**Comment by fgatti675** [comment]
Hi, thanks for reporting and sorry for the delay.
There were some updates in the data import flow that should have fixed it.
I am closing this now. If you think it is not yet resolved, feel free to reopen
